FROM node:16-alpine
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile
COPY prisma ./prisma
RUN npx prisma generate
COPY . .
RUN yarn build
ENV JWT_SECRET=your_jwt_secret_here
EXPOSE 3000
CMD ["yarn", "preview", "--port", "3000"]